server:
  port: 8084

springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservicio_admin
      uri: mongodb://localhost:27017/microservicio_admin
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostame: localhost