server:
  port: 8084

springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservicio_admin
      uri: mongodb://localhost:27017/microservicio_admin