server:
  port: 8086
spring:
  cloud:
    config:
      server:
        git:
          default-label: spring-cloud
          uri: https://github.com/mmolina727/Backend-Monopatin-App
          search-paths: config-data
  application:
    name: Config-server
